# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=dbg
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),dbg)
  prog_config = dbg
  hello_config = dbg
  test_config = dbg
  fnv_config = dbg
  clobber_config = dbg
endif
ifeq ($(config),dist)
  prog_config = dist
  hello_config = dist
  test_config = dist
  fnv_config = dist
  clobber_config = dist
endif

PROJECTS := prog hello test fnv clobber

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

prog: fnv
ifneq (,$(prog_config))
	@echo "==== Building prog ($(prog_config)) ===="
	@${MAKE} --no-print-directory -C . -f prog.make config=$(prog_config)
endif

hello: fnv
ifneq (,$(hello_config))
	@echo "==== Building hello ($(hello_config)) ===="
	@${MAKE} --no-print-directory -C . -f hello.make config=$(hello_config)
endif

test: fnv
ifneq (,$(test_config))
	@echo "==== Building test ($(test_config)) ===="
	@${MAKE} --no-print-directory -C . -f test.make config=$(test_config)
endif

fnv:
ifneq (,$(fnv_config))
	@echo "==== Building fnv ($(fnv_config)) ===="
	@${MAKE} --no-print-directory -C . -f fnv.make config=$(fnv_config)
endif

clobber:
ifneq (,$(clobber_config))
	@echo "==== Building clobber ($(clobber_config)) ===="
	@${MAKE} --no-print-directory -C . -f clobber.make config=$(clobber_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f prog.make clean
	@${MAKE} --no-print-directory -C . -f hello.make clean
	@${MAKE} --no-print-directory -C . -f test.make clean
	@${MAKE} --no-print-directory -C . -f fnv.make clean
	@${MAKE} --no-print-directory -C . -f clobber.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  dbg"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   prog"
	@echo "   hello"
	@echo "   test"
	@echo "   fnv"
	@echo "   clobber"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"